### ISSUE TITLE
GraphInfo causes crash if directed and undirected edges are mixed

### ISSUE THREAD

**Issue by teykamp** [Yonava/magic-graphs#209]
1. create graph with directed edges
2. switch to undirected edges
3. add new undirected edge
4. open graph menu

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify useBaseGraph to support undirected edges and add a toggle for switching between directed and undirected modes.

You can review changes in this commit: https://github.com/mnmnk43434/Yonava-magic-graphs-209/commit/48c586157f7412ae61b1416f17b697b93b9ece9f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by teykamp** [comment]
No longer the case
