### ISSUE TITLE
textarea handler causing memory leaks and exceptions in magic graphs

### ISSUE THREAD

**Issue by Yonava** [Yonava/magic-graphs#256]
https://github.com/user-attachments/assets/3dd3fc59-012a-4890-ad4d-f88ca5f6b641

<img width="812" alt="Screenshot 2024-12-10 at 12 48 16 AM" src="https://github.com/user-attachments/assets/eab09bb4-5093-4673-bf58-ed0cf9e0f17c">

**Comment by teykamp** [comment]
fixed in #258
