### ISSUE TITLE
Tree feature causes tree to be created outside of canvas when used near the edge

### ISSUE THREAD

**Issue by teykamp** [Yonava/magic-graphs#268]
![image](https://github.com/user-attachments/assets/24ac48d6-bec6-40db-bdf1-fd3812cda2f6)

This might be something we ignore for now just like with the farlands...

**Comment by Yonava** [comment]
this is just #188

**Comment by Yonava** [comment]
> ![image](https://private-user-images.githubusercontent.com/46391052/394988508-24ac48d6-bec6-40db-bdf1-fd3812cda2f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjE4OTYsIm5iZiI6MTczNDE2MTU5NiwicGF0aCI6Ii80NjM5MTA1Mi8zOTQ5ODg1MDgtMjRhYzQ4ZDYtYmVjNi00MGRiLWJkZjEtZmQzODEyY2RhMmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA3MzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzQ2YTE3OWI5M2VjYmQ2Y2MyNzU5YmU0ZjI1MmE5YjA1NWQ2NzhjZDkwMWNhNjhiOGY1ZTUyY2MxMjM2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UaDjc5fb2riLPFweJZGjIpTCVZvUAJXVOEE8IyEyqQo)
> 
> This might be something we ignore for now just like with the farlands...

its best to refer to issues using #... like #188 as it creates a link to what you're referring to. GH makes it super easy by revealing a secret smart search menu if you start typing after the # symbol
